import { drizzle, type BetterSQLite3Database } from "drizzle-orm/better-sqlite3";
import { drizzle as drizzleD1 } from "drizzle-orm/d1";
import Database from "better-sqlite3";
import { getCloudflareContext } from "@opennextjs/cloudflare";
import { readdirSync } from "node:fs";
import { join } from "node:path";
import * as schema from "../../drizzle/schema";

// Hand-written instead of generated by `wrangler types` (that command
// needs network access to Cloudflare's API, which this sandbox does not
// have - see docs/PENDING_ITEMS.md). Mirrors wrangler.toml's
// `[[d1_databases]]` block (binding = "DB") exactly; keep both in sync.
//
// Typed `any` rather than the real ambient `D1Database` type on purpose:
// getting that type requires `@cloudflare/workers-types`, whose ambient
// globals (its own `Request`/`Response`/`ReadableStream`/etc.) collide
// with the DOM lib types this Next.js app's ~90 other files already
// compile against everywhere else. Confining the loosened type to this
// one field keeps that blast radius at zero; the actual runtime value in
// production is a genuine D1Database regardless of what TS calls it here.
declare global {
  interface CloudflareEnv {
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    DB: any;
  }
}

/**
 * Database connection (Loop 21, extended Loop 45/46 for real production
 * D1 wiring).
 *
 * PRODUCTION (deployed Cloudflare Workers via the OpenNext adapter): this
 * module returns a `drizzle-orm/d1` instance bound to the real `env.DB`
 * D1 binding declared in wrangler.toml, obtained via
 * `getCloudflareContext()` (the OpenNext adapter sets this on the global
 * scope before any Next.js route handler runs - see
 * node_modules/@opennextjs/cloudflare's `dist/cli/templates/init.js`).
 *
 * LOCAL DEV / EVERY TEST (unit, live-DB, E2E - 290+75 of them as of this
 * loop): `getCloudflareContext()` throws outside a Workers/OpenNext
 * context (this repo deliberately never calls
 * `initOpenNextCloudflareForDev` in next.config.js - it keeps this
 * pre-existing local-D1-file connection instead, so none of the existing
 * tests' behavior changes). What this file does instead, and why it is
 * still genuinely "D1 local, not a second source of truth": `npx
 * wrangler d1 migrations apply DB --local` (the same command every prior
 * loop used) drives Miniflare's real D1 simulator, which stores its data
 * as an ordinary SQLite file under
 * `.wrangler/state/v3/d1/miniflare-D1DatabaseObject/*.sqlite`. This
 * module opens that exact file with better-sqlite3 and wraps it with the
 * same `drizzle/schema.ts` used everywhere else in this repo
 * (sqlite-core table defs are dialect-agnostic between the D1 driver and
 * the better-sqlite3 driver). No schema, table, or row is created here
 * that the checked-in migrations did not already create - if the file
 * or the expected tables are missing, this throws rather than silently
 * creating a divergent schema.
 *
 * IMPORTANT (Loop 46 finding, PEN-044): Cloudflare D1 does not support
 * multi-statement `BEGIN`/`COMMIT` transactions at all - it rejects a
 * raw `BEGIN` statement outright (error 7500, confirmed empirically
 * against the real remote database). `drizzle-orm/d1`'s own
 * `.transaction()` method sends exactly that and WILL crash in
 * production. Do not call `.transaction()` on the value this returns
 * when there is any chance it is the D1 driver - use `runAtomicBatch`
 * below instead, which is safe on both drivers.
 */

const STATE_DIR = join(process.cwd(), ".wrangler", "state", "v3", "d1", "miniflare-D1DatabaseObject");

export class LocalD1NotProvisionedError extends Error {
  constructor(dir: string) {
    super(
      `No local D1 state found at "${dir}". Run ` +
        `\`npx wrangler d1 migrations apply DB --local\` first - this module ` +
        `never creates schema on its own, only connects to what the checked-in ` +
        `migrations already created.`
    );
    this.name = "LocalD1NotProvisionedError";
  }
}

// Loop 27 finding: Miniflare names this file deterministically from
// the binding name + database_id in wrangler.toml, so changing
// database_id (e.g. switching a placeholder to a real one, as this
// loop did) leaves the OLD file behind alongside a freshly created
// one - two real candidates in the same directory at once. Silently
// picking "whichever readdirSync happens to return first" could
// connect the app to stale, orphaned local data without anyone
// noticing. Failing loudly here is safer than guessing.
export class AmbiguousLocalD1StateError extends Error {
  constructor(dir: string, candidates: string[]) {
    super(
      `Found ${candidates.length} candidate local D1 SQLite files in "${dir}": ` +
        `${candidates.join(", ")}. This usually means wrangler.toml's database_id ` +
        `changed and an old file was left behind - delete the stale one(s) and keep ` +
        `only the file matching the current database_id, rather than guessing which to use.`
    );
    this.name = "AmbiguousLocalD1StateError";
  }
}

function resolveLocalD1SqliteFile(): string {
  let entries: string[];
  try {
    entries = readdirSync(STATE_DIR);
  } catch {
    throw new LocalD1NotProvisionedError(STATE_DIR);
  }
  const dbFiles = entries.filter((f) => f.endsWith(".sqlite") && f !== "metadata.sqlite");
  if (dbFiles.length === 0) {
    throw new LocalD1NotProvisionedError(STATE_DIR);
  }
  if (dbFiles.length > 1) {
    throw new AmbiguousLocalD1StateError(STATE_DIR, dbFiles);
  }
  return join(STATE_DIR, dbFiles[0]);
}

export class D1BindingMissingError extends Error {
  constructor() {
    super(
      "Running inside a Cloudflare Workers/OpenNext context but no `DB` " +
        'binding was found on env. Check wrangler.toml\'s [[d1_databases]] ' +
        "block (binding = \"DB\") and the deployed Worker's bindings."
    );
    this.name = "D1BindingMissingError";
  }
}

// getCloudflareContext() throws when called outside an initialized
// Workers/OpenNext context (see the doc comment above) - that throw IS
// the local-vs-production signal this file relies on, so it is caught
// here rather than left to propagate.
function tryGetCloudflareContext() {
  try {
    return getCloudflareContext();
  } catch {
    return undefined;
  }
}

let sqlite: InstanceType<typeof Database> | undefined;
let d1Db: ReturnType<typeof drizzleD1> | undefined;

/**
 * Returns a Drizzle instance - the real Cloudflare D1 binding in
 * production, or the local Miniflare SQLite file everywhere else
 * (dev/test, unchanged from before this loop).
 *
 * Declared/asserted as the local driver's type on purpose: the two
 * drivers' generic types don't unify cleanly (query-builder overload
 * resolution falls apart across a union, breaking type inference in
 * every one of the ~50 files that call this and have nothing to do with
 * D1 vs local), and every route in this repo already only uses the
 * common select/insert/update/delete surface both drivers genuinely
 * share at runtime. The one real behavioral divergence between the two
 * drivers - `.transaction()` crashing on D1 - is deliberately NOT part
 * of that shared surface; it is fenced off entirely inside this file via
 * `runAtomicBatch`, so no caller outside this file should ever call
 * `.transaction()` on the returned value.
 */
export function getDb(): BetterSQLite3Database<typeof schema> {
  const cfContext = tryGetCloudflareContext();
  if (cfContext) {
    if (!cfContext.env.DB) {
      throw new D1BindingMissingError();
    }
    if (!d1Db) {
      d1Db = drizzleD1(cfContext.env.DB, { schema });
    }
    return d1Db as unknown as BetterSQLite3Database<typeof schema>;
  }

  if (!sqlite) {
    // No connection-level SQLite setting is forced here on purpose:
    // none of the checked-in migrations set one either, and a real
    // Cloudflare D1 connection is not this better-sqlite3 object -
    // asserting a setting this local stand-in cannot promise the real
    // D1 runtime shares would not be actually verified. Referential
    // integrity for materials CRUD (this loop's scope) does not depend
    // on it: the materials table has no incoming/outgoing foreign key
    // in play for create/list/deactivate.
    sqlite = new Database(resolveLocalD1SqliteFile());
  }
  return drizzle(sqlite, { schema });
}

/**
 * The `.changes` (rows-affected) count from a `.run()` result, on
 * whichever driver produced it. The two drivers' `.run()` return
 * different shapes: better-sqlite3's has `.changes` directly, while real
 * D1's `.run()` returns a `D1Response` with `.meta.changes` (confirmed
 * against Cloudflare's own docs - see PEN-044). Every route that reads
 * `.changes` off a `.run()`/batch result must go through this rather
 * than reading either field directly, or it silently reads `undefined`
 * on whichever driver it wasn't written against.
 */
export function changesOf(result: { changes: number } | { meta: { changes: number } }): number {
  return "changes" in result ? result.changes : result.meta.changes;
}

/** Any drizzle query builder that hasn't been `.run()` yet - deliberately loose (not
 * parameterized by table/schema) since a single batch legitimately mixes statements
 * against different tables, which don't unify under one generic. */
export type UnrunStatement = { run: () => unknown };

/**
 * Runs a set of prepared writes atomically on whichever driver `getDb()`
 * returned - real D1's `.batch()` in production (its only genuine
 * multi-statement atomic primitive, see PEN-044), or the local
 * better-sqlite3 driver's native `.transaction()` in dev/test (already
 * proven atomic, used throughout this repo before this loop). Callers
 * build `statements` from the SAME `db` instance passed in (e.g.
 * `db.update(pallets).set({...}).where(...)`, NOT `.run()`-ed yet) - do
 * not mix in a `tx`-scoped builder, neither driver here uses one.
 *
 * Returns each statement's result in the same order, in the shape its
 * own execute method (`.run()`/`.all()`/`.get()`) would have produced.
 */
export async function runAtomicBatch(
  db: ReturnType<typeof getDb>,
  statements: readonly [UnrunStatement, ...UnrunStatement[]]
): Promise<unknown[]> {
  if (typeof (db as { batch?: unknown }).batch === "function") {
    return (
      db as unknown as { batch: (s: readonly UnrunStatement[]) => Promise<unknown[]> }
    ).batch(statements);
  }
  return (
    db as unknown as {
      transaction: (fn: (tx: unknown) => unknown[]) => unknown[];
    }
  ).transaction(() => statements.map((s) => s.run()));
}
